# Generated by Django 4.2.9 on 2026-09-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_traineravailability_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeformsubmission',
            name='has_risk_flags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakeformsubmission',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
