# Generated by Django 4.2.9 on 2026-09-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_intakeformsubmission_has_risk_flags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('goals_summary', models.TextField(help_text='Client goals summary & target objectives.')),
                ('baseline_assessment', models.TextField(help_text='Current baseline assessment, posture, fitness level, PAR-Q findings.')),
                ('recommended_program', models.TextField(help_text='Recommended program direction, training frequency, protocols.')),
                ('suggested_timeline', models.TextField(help_text='Suggested timeline, milestones, and evaluation dates.')),
                ('trainer_notes', models.TextField(blank=True, default='', help_text='Additional notes or advisory from trainer.')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='assessment_reports/')),
                ('is_released', models.BooleanField(default=False, help_text='Whether report is released and emailed to client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_report', to='bookings.booking')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assessment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
