# Generated by Django 6.0.7 on 2026-07-14 13:07

import apps.progress.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the weight entry (expected ~every 14 days).')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Always stored in kg; converted to lb in the API response if user prefers.', max_digits=6)),
                ('photo', models.ImageField(blank=True, help_text='Optional progress photo. Stored privately; never publicly accessible.', null=True, upload_to=apps.progress.models.weight_photo_upload_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
