# Generated by Django 4.2.9 on 2026-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='demo_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
