# Generated by Django 6.0.7 on 2026-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Preferred unit for weight entries and workout logs.', max_length=2),
        ),
    ]
