# Generated by Django 6.0.7 on 2026-07-14 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date the workout was actually performed')),
                ('notes', models.TextField(blank=True, help_text="Optional client note, e.g. 'felt heavy'", null=True)),
                ('completed', models.BooleanField(default=False, help_text='True once the client marks the session done')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='The scheduled plan this log fulfills, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-date', '-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_sets', models.PositiveIntegerField(default=1)),
                ('actual_reps', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='exercises.exercise')),
                ('workout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.workoutlog')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
